import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 12.0

[font.bold]
family = "SFMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "SFMono Nerd Font"
style = "Italic"

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[window]
decorations = "none"
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.9
blur = true

[window.padding]
x = 5
y = 5

